/*
 * This file is generated by jOOQ.
 */
package eu.catalkaya.pokertracker.database;


import eu.catalkaya.pokertracker.database.tables.Login;
import eu.catalkaya.pokertracker.database.tables.Player;
import eu.catalkaya.pokertracker.database.tables.Transactions;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>LOGIN</code>.
     */
    public final Login LOGIN = Login.LOGIN;

    /**
     * The table <code>PLAYER</code>.
     */
    public final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>TRANSACTIONS</code>.
     */
    public final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Login.LOGIN,
            Player.PLAYER,
            Transactions.TRANSACTIONS
        );
    }
}
