/*
 * This file is generated by jOOQ.
 */
package eu.catalkaya.pokertracker.database;


import eu.catalkaya.pokertracker.database.tables.Login;
import eu.catalkaya.pokertracker.database.tables.Player;
import eu.catalkaya.pokertracker.database.tables.Transactions;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>LOGIN</code>.
     */
    public static final Login LOGIN = Login.LOGIN;

    /**
     * The table <code>PLAYER</code>.
     */
    public static final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>TRANSACTIONS</code>.
     */
    public static final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;
}
